name: CI - Linux
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - closed
  push:
    branches:
      - 'ci/develop'
      - 'ci/pull_request_test'
  workflow_dispatch:
    inputs:
      runTests:
        description: "Run tests?"
        required: false
        type: boolean
        default: false
jobs:
  call_workflow:
    uses: febiosoftware/febio-workflows/.github/workflows/linux-reusable.yml@develop
    with:
      runTests: ${{ inputs.runTests && true || false }}
      package-name: febio4
      package-sdk: true
      aws-ami-id: ami-0590ebdb5afffb782
    secrets: inherit
