name: CI - Linux - On Push
on:
  push:
    branches:
      - 'ci/develop'
      - 'ci/pull_request_test'
  workflow_dispatch:
    inputs:
      runTests:
        description: "Run tests?"
        required: false
        type: boolean
        default: false
jobs:
  call_workflow:
    uses: tundranerd/febio-workflows/.github/workflows/linux-reusable-push.yml@develop
    with:
      runTests: ${{ inputs.runTests == 'true' }}
      package-name: febio4
      package-sdk: true
      aws-ami-id: ami-0590ebdb5afffb782
    secrets: inherit
