on:
  push:
    branches:
      - 'ci/develop'
  workflow_dispatch:
    inputs:
      runTests:
        description: "Run tests?"
        required: false
        type: boolean
        default: false
jobs:
  call_workflow:
    uses: tundranerd/febio-workflows/.github/workflows/macos-reusable.yml@develop
    with:
      runTests: ${{ inputs.runTests && true || false }}
      package-name: febio4
      package-sdk: true
    secrets: inherit
