name: CI - MacOS Push
on:
  push:
    branches:
      - 'ci/develop'
      - 'ci/pull_request_test'
  workflow_dispatch:
    inputs:
      runTests:
        description: "Run tests?"
        required: false
        default: false
jobs:
  call_workflow:
    uses: tundranerd/febio-workflows/.github/workflows/macos-reusable.yml@develop
    with:
      runTests: ${{ inputs.runTests == 'true' }}
      package-name: febio4
      package-sdk: true
    secrets: inherit
