name: CI - MacOS
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - closed
  push:
    branches:
      - 'ci/develop'
      - 'ci/pull_request_test'
  workflow_dispatch:
    inputs:
      runTests:
        description: "Run tests?"
        required: false
        default: false
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
jobs:
  call_workflow:
    uses: tundranerd/febio-workflows/.github/workflows/macos-reusable.yml@develop
    with:
      runTests: ${{ inputs.runTests == 'true' || github.event_name == 'pull_request' }}
      package-name: febio4
      package-sdk: true
    secrets: inherit
