name: CI - MacOS Pull Request
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - closed
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
jobs:
  call_workflow:
    uses: tundranerd/febio-workflows/.github/workflows/macos-reusable.yml@develop
    with:
      runTests: true
      package-name: febio4
      package-sdk: true
    secrets: inherit
