name: CI
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronized
      - closed
  push:
    branches:
      - 'ci/develop'
      - 'ci/pull_request_test'
  workflow_dispatch:
    inputs:
      runTests:
        description: "Run tests?"
        required: false
        default: false

jobs:
  call_workflow:
    uses: febiosoftware/febio-workflows/.github/workflows/macos-reusable.yml@develop
    with:
      runTests: ${{ inputs.runTests == 'true' || github.event_name == 'pull_request' }}
      package-name: febio4
      package-sdk: true
    secrets: inherit
